/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Drag;

import Drag.Register;
import GUI.*;
import pharmacyapp.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import sun.security.util.Password;

/**
 *
 * @author ajocme_sd2022
 */
public class Login extends javax.swing.JFrame {
//    JTextField LoginUsername = new JTextField();
//    JPasswordField LoginPassword = new JPasswordField();

    ArrayList<String> UserName = new ArrayList<>();
    ArrayList<String> Passwords = new ArrayList<>();

    /**
     * Creates new form JFrame
     */
    public Login() {
        initComponents();

        try {
            // create our mysql database connection
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost/PharmacyApp";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");

            // our SQL SELECT query.
            // if you only need a few columns, specify them by name instead of using "*"
            String query = "SELECT * FROM register";

            // create the java statement
            Statement st = conn.createStatement();

            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);

            // iterate through the java resultset
            while (rs.next()) {
                int id = rs.getInt("id");
                String username = rs.getString("UserName");
                //int age = rs.getInt("age");
                String pass = rs.getString("Password");
                if (UserName.contains(username) && Passwords.contains(pass)) {
                    continue;
                } else {
                    UserName.add(username);
                    Passwords.add(pass);
                }
            }
            st.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JPasswordField();
        drop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ajocme_sd2022\\Pictures\\asset.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Login as");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 210, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 120, 22);

        UsernameTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(UsernameTextField);
        UsernameTextField.setBounds(150, 50, 290, 40);

        Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(340, 210, 90, 40);

        PasswordTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(PasswordTextField);
        PasswordTextField.setBounds(150, 130, 290, 40);

        drop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Pharmacist" }));
        drop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropMouseClicked(evt);
            }
        });
        drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropActionPerformed(evt);
            }
        });
        jPanel1.add(drop);
        drop.setBounds(150, 210, 100, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Username : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 62, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 700, 490);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login Form");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 0, 330, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
                String a = "Cutomer";
                String b = "Pharmacist";
//                String dropDownValue = drop.getSelectedItem().toString();
//                String choice = dropDownValue;
//                
        if ((drop.getSelectedItem().toString()).equals("Customer")) {
//            JOptionPane.showMessageDialog(null, "Customer!");
             new DCustomer().setVisible(true);
        }else{
//            JOptionPane.showMessageDialog(null, "Pharmacist");
            new DPharmacist().setVisible(true);
        }
        
        
      
//    if (dropDownValue.equals(a) == true) {
        if ( UserName.contains(UsernameTextField.getText()) && Passwords.contains(PasswordTextField.getText())) {
//                JOptionPane.showMessageDialog(null, "Successfully Login!");
//                new DCustomer().setVisible(true);

            } else if (!UserName.contains(UsernameTextField.getText()) && Passwords.contains(PasswordTextField.getText())) {
//                JOptionPane.showMessageDialog(null, "Wrong Password/Username");
                UsernameTextField.setText("");
                PasswordTextField.setText("");
                UsernameTextField.requestFocus();
                Login home = new Login();
                dispose();
                home.setVisible(true);

            } else if (UserName.contains(UsernameTextField.getText()) && !Passwords.contains(PasswordTextField.getText())) {
//                JOptionPane.showMessageDialog(null, "Wrong Password/Username");
                UsernameTextField.setText("");
                PasswordTextField.setText("");
                UsernameTextField.requestFocus();
                 Login home = new Login();
                dispose();
                home.setVisible(true);
               
            } else {
//                JOptionPane.showMessageDialog(null, "Wrong Username && Password !!!!");
                UsernameTextField.setText("");
                PasswordTextField.setText("");
                UsernameTextField.requestFocus();
                Login home = new Login();
                dispose();
                home.setVisible(true);
               
            }
//        }else{
//        new Dashboard().setVisible(true);
//    }
           
      
       

     


    }//GEN-LAST:event_LoginMouseClicked

    private void dropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropMouseClicked

    private void dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
                Login login = new Login();
                login.toBack();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JComboBox<String> drop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
