/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Drag;

import pharmacyapp.*;
import GUI.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ajocme_sd2022
 */
public class Register extends javax.swing.JFrame {
    private ArrayList<Account> accounts;
     private ArrayList<String> age;
   

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        registerfullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        registerusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        registerage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        login_btn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        registeraddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        registerpassword = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        jLabelLogin2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        registerfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerfullnameActionPerformed(evt);
            }
        });
        jPanel1.add(registerfullname);
        registerfullname.setBounds(120, 120, 290, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("UserName : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 180, 110, 17);

        registerusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerusernameActionPerformed(evt);
            }
        });
        jPanel1.add(registerusername);
        registerusername.setBounds(120, 170, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Age  : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 220, 50, 30);

        registerage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerageActionPerformed(evt);
            }
        });
        jPanel1.add(registerage);
        registerage.setBounds(120, 220, 290, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 280, 80, 15);

        login_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_btn.setText("LOGIN");
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        jPanel1.add(login_btn);
        login_btn.setBounds(280, 410, 50, 20);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registration ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 450, 80);
        jPanel1.add(registeraddress);
        registeraddress.setBounds(120, 320, 290, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Address:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 320, 70, 30);

        registerpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(registerpassword);
        registerpassword.setBounds(120, 270, 290, 30);

        Register.setText("Register");
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
        });
        jPanel1.add(Register);
        Register.setBounds(320, 370, 90, 30);

        jLabelLogin2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLogin2.setText("Have an account already?");
        jLabelLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogin2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLogin2);
        jLabelLogin2.setBounds(120, 410, 160, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Full Name : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 130, 100, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerusernameActionPerformed

    private void registerageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerageActionPerformed

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
       Login login = new Login();
       dispose();
       login.setVisible(true);
    }//GEN-LAST:event_login_btnMouseClicked

    private void registerfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerfullnameActionPerformed
    
    }//GEN-LAST:event_registerfullnameActionPerformed

    private void registerpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerpasswordActionPerformed
       
    }//GEN-LAST:event_registerpasswordActionPerformed

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked

        try {
            // create a mysql database connection
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost/PharmacyApp";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
            
            // the mysql insert statement
            //register is the register name for the table in the database
            String query = " insert into register(fullname,username,age,password,address)"
                    + " values (?,?,?,?,?)";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, registerfullname.getText());
            preparedStmt.setString(2, registerusername.getText());
            preparedStmt.setString(3, registerage.getText());
            preparedStmt.setString(4, registerpassword.getText());
            preparedStmt.setString(5, registeraddress.getText());
            
            // execute the preparedstatement
            preparedStmt.execute();
            
            conn.close();
             String age = registerage.getText();
       int edad = Integer.parseInt(age);    
       if ( edad < 18) {
          JOptionPane.showMessageDialog(null, "Sorry!Underage are not allowed to register!");
        } else {
           Login login = new Login();
           dispose();
           login.setVisible(true);
           JOptionPane.showMessageDialog(this, "This data is Saved!");
       }
        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
//        Login login = new Login();
//            dispose();
//            login.setVisible(true);
//           
          
    }//GEN-LAST:event_RegisterMouseClicked

    private void jLabelLogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogin2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLogin2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Register().setVisible(true);
                Register reg = new Register();
                reg.toBack();
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel login_btn;
    private javax.swing.JTextField registeraddress;
    private javax.swing.JTextField registerage;
    private javax.swing.JTextField registerfullname;
    private javax.swing.JPasswordField registerpassword;
    private javax.swing.JTextField registerusername;
    // End of variables declaration//GEN-END:variables
}

//String age = aField.getText();
//               int edad = Integer.parseInt(age);
////                User newUser = new User(unameField.getText(),eField.getText(),edad,pField.getText());
//               if(option.equals("Pharmacist") && edad >= 18){
//                   rose.addUser(new Pharmacist(unameField.getText(),eField.getText(),edad,pField.getText()));
//               }else if(option.equals("Customer")){
//                   if(edad < 18){
//                       JOptionPane.showMessageDialog(null,"Sorry! Underage not allowed to register");
//                   }else if(edad >= 18 && edad <= 59){
//                       rose.addUser(new Adult(unameField.getText(),eField.getText(),edad,pField.getText()));
//                   }else{
//                       rose.addUser(new SeniorCitizen(unameField.getText(),eField.getText(),edad,pField.getText()));
//                   }
//               }
